---
name: "Smarter Playlist"
guid: "3311dfd2-fe3b-4367-a3f0-0dcea5ba07cd"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Short description about your plugin"
description: >
  This is a longer description that can span more than one
  line and include details about your plugin.
category: "General"
owner: "poindexter12"
artifacts:
- "Jellyfin.Plugin.SmarterPlaylist.dll"
changelog: >
  changelog
