name: '🧪 Test Plugin'

permissions: read-all

on:
  push:
    branches:
      - main
      - feature/*
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
      - feature/*
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/test.yaml@master
